identifier-prefix: ogc.geo.topo.

name: Topo-Feature
abstract: Features with geometry defined via  generalised topology between identified objects (Features).
description: |
  Defines Feature (object) topology using a _topology_ property to reference an ordered list of references to other features. 

  Other features may be either features with topology properties or GeoJSON (or FG-JSON) geometry properties.

  Topo-Feature defined objects can be solids, swept volumes or any other concept. 
  
  Topo-Feature allows for general topology to be described between independent features (objects) with any geometry dimensions. 
  
  Topo-Feature-Collections define a self-contained set of such objects with referential integrity (all elements are present to fully define geometry coordinates.
  
  Note: This is a generalisation of the TopoJSON concept using inline, nested arrays of coordinates - but not limited to self-contained geometries per feature, duplicated between topologically related features.. 
  
  _Topo-Feature allows for explicit CRS. If desired coordinate compaction transformations could be defined as per TopoJSON functionality, using specialised CRS definition._


